name: Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # لجلب جميع الفروع

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build APK
        run: cmd.exe /c gradlew.bat assembleRelease

      - name: Sign APK
        run: cmd.exe /c java.exe -jar "signer\\ApkSigner.jar" sign --key "signer\\apkeasytool.pk8" --cert "signer\\apkeasytool.pem" --v4-signing-enabled false --out "%cd%\\app\\build\\outputs\\apk\\release\\youtube_pro_signed.apk" "%cd%\\app\\build\\outputs\\apk\\release\\app-release-unsigned.apk"

      - name: Generate timestamped APK filename
        id: timestamp
        shell: bash
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          echo "timestamp=$TIMESTAMP" >> $GTB_TOKEN

      - name: Commit APK to APK branch
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # التأكد من وجود الفرع APK أو إنشاؤه
          if git show-ref --quiet refs/heads/APK; then
            git checkout APK
          else
            git checkout --orphan APK
            git rm -rf .
            git commit --allow-empty -m "Initialize APK branch"
            git push origin APK
            git checkout APK
          fi

          # نسخ ملف APK الموقع من الفرع الرئيسي إلى الفرع APK
          git checkout main -- app/build/outputs/apk/release/youtube_pro_signed.apk

          # إعادة تسمية الملف مع تضمين الطابع الزمني
          mv app/build/outputs/apk/release/youtube_pro_signed.apk youtube_pro_signed_${{ steps.timestamp.outputs.timestamp }}.apk

          git add youtube_pro_signed_${{ steps.timestamp.outputs.timestamp }}.apk
          git commit -m "Add signed APK with timestamp ${{ steps.timestamp.outputs.timestamp }}"
          git push origin APK



