name: Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      run: cmd.exe /c gradlew.bat assembleRelease

    - name: Sign
      run: cmd.exe /c java.exe -jar "signer\\ApkSigner.jar" sign --key "signer\\apkeasytool.pk8" --cert "signer\\apkeasytool.pem" --v4-signing-enabled false --out "%cd%\\app\\build\\outputs\\apk\\release\\youtube_pro_signed.apk" "%cd%\\app\\build\\outputs\\apk\\release\\app-release-unsigned.apk"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Apk
        path: "app/build/outputs/apk/release/youtube_pro_signed.apk"

    - name: Copy APK to APK folder
      run: |
        mkdir APK
        copy app\\build\\outputs\\apk\\release\\youtube_pro_signed.apk APK\\youtube_pro_signed.apk

    - name: Commit and Push APK
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GTB_TOKEN }}
        branch: APK
        directory: .
        message: "Add signed APK to APK folder"
