name: Gradle

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build APK
        run: cmd.exe /c gradlew.bat assembleRelease

      - name: Sign APK
        run: cmd.exe /c java.exe -jar "signer\\ApkSigner.jar" sign --key "signer\\apkeasytool.pk8" --cert "signer\\apkeasytool.pem" --v4-signing-enabled false --out "%cd%\\app\\build\\outputs\\apk\\release\\youtube_pro_signed.apk" "%cd%\\app\\build\\outputs\\apk\\release\\app-release-unsigned.apk"

      - name: Copy signed APK to APK folder
        shell: bash
        run: |
          if [ ! -f "app/build/outputs/apk/release/youtube_pro_signed.apk" ]; then
            echo "Signed APK not found!"
            exit 1
          fi

          mkdir -p APK
          cp "app/build/outputs/apk/release/youtube_pro_signed.apk" "APK/youtube_pro_signed.apk"

      - name: Commit APK to main branch
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add APK/youtube_pro_signed.apk
          git commit -m "Update signed APK [ci skip]" || echo "No changes to commit"
          git push origin main
